name: Build and Push Container

on:
  push:
    branches: [ main ]  # ou la branche de ton choix
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (pour multi-arch, optionnel)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (optionnel)
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repository owner lowercase
        id: repo_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./Forge/base-container
          push: true
          tags: ghcr.io/${{ steps.repo_owner.outputs.owner }}/archimedeos-base:latest